### ISSUE TITLE
problem.

### ISSUE THREAD

**Issue by crumpx** [FreeCodeCamp/fcc-expressworks#6]
WHAT'S IN QUERY
 Exercise 7 of 8

verify will not passed with correct code, even the solution.js

Error:

"Cannot GET /search/?results=recent&amp;type=quote&amp;page=3" !=    "{\"results\":\"recent\",\"type\":\"quote\",\"page\":\"3\"}"
   ""                                  !=

**Comment by BerkeleyTrue** [comment]
Please use https://gitter.im/FreeCodeCamp/Help when stuck.

Happy Coding
